### ISSUE TITLE
Initiating a Call 

### ISSUE THREAD

**Issue by GoyalPriyanka** [nexmo-community/client-sdk-click-to-call#5]
I have downloaded the code and purchased a kenya number and now trying to make a call. 
After clicking the "Call" button, "Knocking" api is called which in turn created a conversation and returned the UUID and member but then It called : 
Request URL: https://api.nexmo.com/beta/conversations/:conversationsId/rtc
which returns,
code: "conversation:error:not-allowed"
description: "The request failed because the current state of the conversation is INACTIVE. Only GET and DELETE conversation requests are allowed."
the above response. 

Searched but could not find any solution.

**Comment by conshus** [comment]
Hello @GoyalPriyanka,

From your issue, it looks as if the Conversation Id is not being sent.

We recently merged some changes to the repo.
In your .env file, do you have `SUPPORT_PHONE_NUMBER`? That should be `NEXMO_NUMBER`.

Also, when calling the server, previously the code in the client.js around line 34 was `application.callServer();` it is now `application.callServer(application.me.name);`

Let me know if this works for you.
Thanks.
Dwane

**Comment by jainam-techuz** [comment]
Hello,

I am facing an issue like I can initiate the call from call now button and it is working, but the thing is I'm not able to receive actual call on my phone number, in console it is showing answered but my phone not ringed yet, also I'm not able to get this message `Thank you for calling Acme support. Transferring you now.`, please do the needful.

Note: I'm using free trail version.

**Comment by conshus** [comment]
Hi jainam-techuz,

That's strange that it would show it being answered if your phone isn't ringing.

A couple of things to check:
- make sure that in your NCCO, you have your country code in front of your phone number and no symbols ex: + - ()
- if you aren't getting "Thank you for calling Acme support. Transferring you now." and it's in your NCCO, your NCCO may not be available by the application. Where is the NCCO hosted?

We have a tutorial on making a phone call from a web application using GitHub Gists here: https://developer.nexmo.com/client-sdk/tutorials/app-to-phone/introduction/javascript

Let us know if any of this helps.

Thanks.

**Comment by jainam-techuz** [comment]
Hello

Thanks for getting back to me.

Yes It worked for me thank you for your help.

**Comment by jainam-techuz** [comment]
Hello,

Can you share me steps from where I can delete my test numbers as I have
added 5 test numbers and I want to add another test number, can you please
provide me steps to do this?


Regards,
Jainam Shah
Full Stack Developer
www.techuz.com <http://techuz.com/>
Mob: +91-8905033460

**Comment by conshus** [comment]
When you say "test numbers", you mean the Nexmo/Vonage numbers purchased?
If that is what you mean, in your dashboard ( https://dashboard.nexmo.com/your-numbers ), go to "Numbers" -> "Your numbers" and click the red trash can next to the number you'd like to delete.

You may need to add more money to your account if you want to purchase more numbers.

Hope that helps. Let me know if you need more information.

Thanks.

**Comment by pardel** [comment]
@jainam-techuz you can also use the CLI: `nexmo number:cancel`

Here is the help info:

```
% nexmo number:cancel --help
Usage: number:cancel|nc [options] <number>

Cancel a number you own

Options:
  --confirm                          skip confirmation step and directly cancel the number
  -c, --country_code [country_code]  manually provide the country code, overriding a dynamic lookup
  -h, --help                         output usage information
  Examples:

    $ nexmo number:cancel 445555555555
    $ nexmo number:cancel 31555555555
    $ nexmo number:cancel 17136738555

```

Will close this for now. Please re-open if you still require assistance. Thank you!
